apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example
  labels:
    name: example
spec:
  replicas: 7
  selector:
    matchLabels:
      name: example
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: example
    spec:
      containers:
      - image: mmorejon/erase-una-vez-1:0.2.0
        name: erase-una-vez-1
        env:
          - name: CHARACTER
            value: "un elfo."
