apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-04
  labels:
    app: server-04
    example: fourth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-04
  template:
    metadata:
      labels:
        app: server-04
        example: fourth
    spec:
      containers:
        - name: server
          image: ghcr.io/mmorejon/erase-una-vez-2:v0.2.1
          command:
            - server
          ports:
            - name: http-server
              containerPort: 8000
