apiVersion: v1
kind: Namespace
metadata:
  name: square
  labels:
    example: third
    type: server

---
apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: square
  labels:
    example: third
    type: server
spec:
  containers:
    - name: server
      image: ghcr.io/mmorejon/erase-una-vez-2:v0.2.1
      command:
        - server
      env:
        - name: CHARACTER
          value: "un libro sobre Kubernetes."
      ports:
        - name: http-server
          containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: square
  labels:
    example: third
    type: server
spec:
  type: ClusterIP
  selector:
    type: server
  ports:
  - name: http-server
    port: 8000
    protocol: TCP
    targetPort: http-server

---
apiVersion: v1
kind: Namespace
metadata:
  name: circle
  labels:
    example: third
    type: client

---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: circle
  labels:
    example: third
    type: client
spec:
  containers:
    - name: client
      image: ghcr.io/mmorejon/erase-una-vez-2:v0.2.1
      command:
        - client
      env:
        - name: SERVER_URL
          value: "http://server.square:8000"
        - name: ENDPOINT
          value: "/echo"
        - name: SLEEP_TIME
          value: "3s"