apiVersion: v1
kind: Namespace
metadata:
  name: blue
  labels:
    example: second
    space: blue

---
apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: blue
  labels:
    example: second
spec:
  containers:
    - name: message
      image: ghcr.io/mmorejon/erase-una-vez-1:v0.2.1

---
apiVersion: v1
kind: Namespace
metadata:
  name: green
  labels:
    example: second
    space: green

---
apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: green
  labels:
    example: second
spec:
  containers:
    - name: mensaje
      image: ghcr.io/mmorejon/erase-una-vez-1:v0.2.1
