apiVersion: v1
kind: Secret
metadata:
  name: secret-03
  labels:
    app: secret-03
data:
  CHARACTER: dW4tcGFsYWNpbw==
  SLEEP_TIME: NQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-secret-03
  labels:
    app: secret-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-03
  template:
    metadata:
      labels:
        app: secret-03
    spec:
      containers:
        - name: container-01
          image: mmorejon/erase-una-vez-1:0.2.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: secret-03